大まかな機能作成完了
zau-works/ChatDictionary pull request #1
Opened 2022-12-25 16:44 UTC by Sakaki-Aruka

大体の機能を書きました

2022-12-25 16:47 UTC, Sakaki-Aruka commented
まだ終わっていないこと
・データを保存する機能を書く
・plugin.yml への追記
・commandExecutor の登録

2022-12-26 12:55 UTC, zau-works requested changes
とりあえず見ました。いくつか修正してほしい部分があったので、修正お願いします！
あと、全体的にコードフォーマットを反映することはできますかね？
（IntelliJ で `Ctrl+ Alt + L` を押すと反映できます）

2022-12-26 12:55 UTC, zau-works commented on src/main/java/com/github/zauworks/chatdictionary/command/DictionaryManager.java
> +public class DictionaryManager implements CommandExecutor {
クラス名は `DictionarySettingCommand` でお願いします。
これだと Manager クラスなのか Command クラスなのか、ややこしくなっちゃうので。

2022-12-26 12:55 UTC, zau-works commented on src/main/java/com/github/zauworks/chatdictionary/command/DictionaryManager.java
> +    public boolean onCommand(CommandSender sender, Command command,String label,String[] args){
こちら、管理用コマンドになりますので、権限を判定する処理がほしいですね。
権限ノードはとりあえず `dictionary.command.setting` でいいかな。

2022-12-26 12:55 UTC, zau-works commented on src/main/java/com/github/zauworks/chatdictionary/command/DictionaryManager.java
> +        Player player = (Player) sender;
このままだとコンソールからコマンドを打ったときにエラー吐いちゃうと思うので、とりあえず暫定でもいいので**コンソールからコマンドを打ったときの処理**を実装お願いします（とりあえずメッセージ表示するだけでもおｋです）。

2022-12-26 12:55 UTC, zau-works commented on src/main/java/com/github/zauworks/chatdictionary/command/DictionaryManager.java
> +            player.sendMessage(new Messages().error("Invalid arguments."));
```suggestion
player.sendMessage(new Messages().error("[Error]:Word not specified."));
```

こんな感じに表示した方がいいかな？

2022-12-26 12:55 UTC, zau-works commented on src/main/java/com/github/zauworks/chatdictionary/command/DictionaryManager.java
> +        if(type.equalsIgnoreCase("add") && args.length >= 3){
`add` や `remove` などの引数が指定された場合において、ここでしか `args` の length を判定してないので、このままだと `add` 以外の引数を指定したときに引数を参照できずにエラー吐いちゃう可能性が出てくると思います。  
とりあえずここより前か、`add` や `remove` などの引数の処理内、または `add` 以外のところにも似たような処理を書くと良いかもしれません。

2022-12-26 12:55 UTC, zau-works commented on src/main/java/com/github/zauworks/chatdictionary/command/DictionaryManager.java
> +            if(word.contains(" "))word.replace(" ","+");
ここの処理たぶん、コマンドの引数はスペースで区切って指定するので、ここでスペースが「＋」に置換されることはないですね。となると、無駄な処理になるので、削除しちゃってもいいかもです。
あと「＋」についてはプレイヤーに、**スペースとして判定してもらいたい部分**に直接指定してもらうことになるので、ここで処理する必要もないかなぁと（これについては渡した仕様書での書き方が悪かったですね。すみません）。

2022-12-26 12:55 UTC, zau-works commented on src/main/java/com/github/zauworks/chatdictionary/command/DictionaryManager.java
> +            ChatDictionary.getDictionaryWords().put(word,dictWord);
ワードを追加した旨のメッセージを表示したいですね。

2022-12-26 12:55 UTC, zau-works commented on src/main/java/com/github/zauworks/chatdictionary/command/DictionaryManager.java
> +            ChatDictionary.getDictionaryWords().remove(args[1]);
ワードを削除した旨のメッセージを表示したいですね。

2022-12-26 12:55 UTC, zau-works commented on src/main/java/com/github/zauworks/chatdictionary/command/DictionaryManager.java
> +            if(word.contains(" "))word.replace(" ","+");
ここも消しちゃってもおｋです。

2022-12-26 12:55 UTC, zau-works commented on src/main/java/com/github/zauworks/chatdictionary/command/DictionaryManager.java
> +                player.sendMessage(new Messages().error("[Word modify Error]:Invalid option-type\nArguments: <bold | underline | color | mean>"));
`sendMessage()` って改行コード対応してましたっけ？

2022-12-26 12:55 UTC, zau-works commented on src/main/java/com/github/zauworks/chatdictionary/command/DictionaryManager.java
> +                dict.setBold(bool);
対応していないタイプの値が指定されたときにメッセージ表示したいですね。

2022-12-26 12:55 UTC, zau-works commented on src/main/java/com/github/zauworks/chatdictionary/command/DictionaryManager.java
> +                dict.setUnderline(bool);
対応していないタイプの値が指定されたときにメッセージ表示したいですね。

2022-12-26 12:55 UTC, zau-works commented on src/main/java/com/github/zauworks/chatdictionary/command/DictionaryManager.java
> +                wordReload(word);
ワードの設定のリロードに成功した旨のメッセージを表示したいですね。

2022-12-26 12:55 UTC, zau-works commented on src/main/java/com/github/zauworks/chatdictionary/command/DictionaryManager.java
> +                configReload();
config のリロードに成功した旨のメッセージを表示したいですね。

2022-12-26 12:55 UTC, zau-works commented on src/main/java/com/github/zauworks/chatdictionary/command/DictionaryManager.java
> +        Pattern p = Pattern.compile("[1-9|a-g|k-o|r]");
https://htmlcolorcodes.com/minecraft-color-codes/
このサイトにあるカラーコードのみをカラーコードとして指定できるようにしたいですね。

2022-12-26 12:55 UTC, zau-works commented on src/main/java/com/github/zauworks/chatdictionary/command/DictionaryManager.java
> +        ChatDictionary.getDictionaryWords().remove(word);
１５０行目で新しく生成した DictionaryWord を put してるので、ここはなくても大丈夫かも？

2022-12-26 13:04 UTC, zau-works commented
修正箇所の修正、およびコマンドのテストが終わり次第に、問題がなければ通しますので、

・plugin.yml への追記
・commandExecutor の登録

の方を優先的にお願いします！

2022-12-26 14:26 UTC, Sakaki-Aruka commented on src/main/java/com/github/zauworks/chatdictionary/command/DictionaryManager.java
> +                dict.setBold(bool);
true | false 以外の値が指定された時、メッセージを表示すると同時に処理を抜けるようにした方が良いですか？

2022-12-27 08:56 UTC, Sakaki-Aruka commented
諸々の機能を追加しました

2022-12-27 11:27 UTC, zau-works requested changes
見ました。
一部、新しくコミットされた部分にコードフォーマットが反映されてなかったので、反映お願いします。

2022-12-27 11:27 UTC, zau-works commented on src/main/java/com/github/zauworks/chatdictionary/ChatDictionary.java
> +        getCommand("dictionary").setExecutor(new DictionarySettingCommand());
ここ、 `getLogger()` より前に `getCommand()` を書くようにお願いします。

2022-12-27 11:27 UTC, zau-works commented on src/main/java/com/github/zauworks/chatdictionary/command/DictionarySettingCommand.java
> +        if (type.equalsIgnoreCase("add") && args.length >= 3) {
ここの `args` の判定は消しちゃいましょう。
```suggestion
        if (type.equalsIgnoreCase("add")) {
```

2022-12-27 11:27 UTC, zau-works commented on src/main/java/com/github/zauworks/chatdictionary/command/DictionarySettingCommand.java
> +    }
ここらへんも `DataSave` にまとめちゃってもいいかもです。

2022-12-27 11:27 UTC, zau-works commented on src/main/java/com/github/zauworks/chatdictionary/util/DataSave.java
> +public class DataSave {
もうちょっとクラスとしてわかりやすくするために `DictionaryData` にリネームしちゃいましょうか。
パッケージも `com.github.zauworks.chatdictionary.dictionary` （=Dictionary関連のパッケージ）に移動しておいてください。

2022-12-27 11:27 UTC, zau-works commented on src/main/resources/plugin.yml
> +    /dictionary <add|remove|options|config reload> ...
プラグインのロード時にエラー吐いてますので、修正お願いします。

```suggestion
commands:
  dictionary:
    description: 辞書のワードを追加、削除、設定するためのコマンドです。
    permission: dictionary.command.setting
    usage: /dictionary <add|remove|options|config reload> ...
```

2022-12-27 13:37 UTC, zau-works approved these changes
修正ありがとうございます！

一部メッセージ表示の挙動が気になりましたが、こちらは僕の方で整えようと思います。
他は問題なく動くことを確認しましたのでマージします！
ありがとうございました！

2022-12-27 13:40 UTC, merged